FROM centos
COPY . /workspace
WORKDIR /workspace
CMD ["./automation.sh"]
#ENV container docker
#RUN yum install docker -y
#RUN yum update -y
#RUN curl -fsSL https://get.docker.com | sh;
#RUN yum install docker-engine -y
#RUN service docker start